# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de5ab32d539b0be19c6712b20a8f03ba2524f53489addaaefed7b863b818e12f1251a8869b8ca339a7ba9c7ef562ab4663c198a52fb85530599cf694b44e1aa6

test:
  secret_key_base: 0c45945b13981ca1d3dded3419a749a3df464ba1f6720ec15991b143bfd68e3b240752c1cb31bad058f324745f73a4a14bcb457ee0791f69ce73789fad465caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
